import React, { useMemo, useState } from "react";
import { Activity as ActivityIcon, CheckCircle2, Filter, MessageSquare, Search, Siren, Terminal } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function Activity() {
  const [query, setQuery] = useState("");
  const incidents = trpc.incidents.list.useQuery().data ?? [];
  const events = useMemo(() => incidents.flatMap(item => [{ id: `${item.id}-created`, type: "Alert received", detail: `${item.alert.serviceName} reported ${item.alert.message}`, at: item.createdAt, icon: Siren }, { id: `${item.id}-decision`, type: "AI decision generated", detail: `${item.classification.severity} · ${item.runbook.title}`, at: item.createdAt, icon: ActivityIcon }, ...(item.resolvedAt ? [{ id: `${item.id}-resolved`, type: "Incident resolved", detail: item.actionResult ?? "Remediation completed", at: item.resolvedAt, icon: CheckCircle2 }] : [])]).filter(item => `${item.type} ${item.detail}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => b.at.localeCompare(a.at)), [incidents, query]);
  return <div className="space-y-6"><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-slate-400">Audit trail</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Activity log</h2><p className="mt-2 text-sm text-slate-500">A transparent timeline of alerts, decisions, approvals, and outcomes.</p></div><Card className="border-0 bg-white shadow-sm"><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><CardTitle className="text-lg">Recent events</CardTitle><div className="relative sm:w-72"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Filter events" className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2 pl-9 pr-3 text-sm" /></div></div></CardHeader><CardContent>{events.length === 0 ? <div className="py-20 text-center"><Filter className="mx-auto h-6 w-6 text-slate-300" /><p className="mt-3 text-sm font-medium text-slate-500">No activity to display</p><p className="mt-1 text-xs text-slate-400">Simulate an incident to create an auditable event trail.</p></div> : <div className="relative space-y-0 pl-2 before:absolute before:bottom-5 before:left-[22px] before:top-5 before:w-px before:bg-slate-200">{events.map(event => <div key={event.id} className="relative flex gap-4 py-4"><div className="z-10 grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-slate-200 bg-white text-indigo-600"><event.icon className="h-4 w-4" /></div><div className="min-w-0 flex-1 rounded-2xl border border-slate-100 bg-slate-50/70 p-4"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">{event.type}</p><Badge variant="outline" className="text-[10px]">{new Date(event.at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</Badge></div><p className="mt-1 text-sm text-slate-500">{event.detail}</p></div></div>)}</div>}</CardContent></Card></div>;
}
