import React from "react";
import { Activity, ArrowRight, Clock3, FileText, ShieldCheck, Siren, Sparkles, Users } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { PlainLanguageGuide } from "@/components/PlainLanguageGuide";

export default function Home() {
  const utils = trpc.useUtils();
  const statusQuery = trpc.service.status.useQuery(undefined, { refetchInterval: 2500 });
  const incidentsQuery = trpc.incidents.list.useQuery();
  const fail = trpc.service.simulateFailure.useMutation();
  const create = trpc.incidents.create.useMutation();
  const restore = trpc.service.restore.useMutation();
  const healthy = statusQuery.data?.status === "healthy";
  const incidents = incidentsQuery.data ?? [];
  const critical = incidents.filter(item => item.classification.severity === "Critical").length;

  const refresh = () => { void utils.service.status.invalidate(); void utils.incidents.list.invalidate(); };
  const simulate = async () => { await fail.mutateAsync(); const incident = await create.mutateAsync(); toast.error("Critical incident created", { description: `${incident.id} is ready for review.` }); refresh(); };
  const recover = async () => { await restore.mutateAsync(); toast.success("Payment service restored"); refresh(); };

  return <div className="space-y-7">
    <PlainLanguageGuide />
    <section className="grid gap-5 xl:grid-cols-[1.4fr_.9fr]"><Card className="overflow-hidden border-0 bg-[#101a2c] text-white shadow-[0_18px_50px_rgba(16,26,44,.14)]"><CardContent className="relative p-7 md:p-9"><div className="absolute right-0 top-0 h-52 w-52 rounded-full bg-[#9bf2cb]/10 blur-2xl" /><div className="relative max-w-xl"><div className="mb-5 flex items-center gap-2 text-xs font-medium uppercase tracking-[0.2em] text-[#9bf2cb]"><span className="h-2 w-2 rounded-full bg-[#9bf2cb]" />Live control plane</div><h2 className="text-3xl font-semibold leading-tight tracking-tight md:text-4xl">Keep critical services calm under pressure.</h2><p className="mt-4 max-w-lg text-sm leading-6 text-slate-400">Turn noisy signals into clear, approval-safe decisions grounded in your team’s runbooks.</p><div className="mt-7 flex flex-wrap gap-3"><Button className="bg-[#9bf2cb] text-[#0b1220] hover:bg-[#b8f8dc]" onClick={simulate} disabled={fail.isPending || create.isPending}><Siren className="mr-2 h-4 w-4" />Simulate incident</Button><Button variant="outline" className="border-white/15 bg-white/5 text-white hover:bg-white/10 hover:text-white" onClick={recover}><Activity className="mr-2 h-4 w-4" />Restore service</Button></div></div></CardContent></Card><Card className="border-0 bg-white shadow-[0_12px_35px_rgba(30,41,59,.06)]"><CardHeader><p className="text-xs font-medium uppercase tracking-[0.18em] text-slate-400">Monitored service</p><CardTitle className="mt-2 text-xl tracking-tight">Checkout API</CardTitle></CardHeader><CardContent><div className={`flex items-center gap-2 rounded-xl px-4 py-3 text-sm font-semibold ${healthy ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}><span className={`h-2.5 w-2.5 rounded-full ${healthy ? "bg-emerald-500" : "bg-red-500"}`} />{healthy ? "Healthy" : "Unhealthy"}<span className="ml-auto text-xs font-normal">payment-service</span></div><div className="mt-5 flex items-end justify-between"><div><p className="text-3xl font-semibold">99.98%</p><p className="mt-1 text-xs text-slate-500">Availability · last 24 hours</p></div><Activity className="h-7 w-7 text-emerald-500" /></div><div className="mt-5 flex h-12 items-end gap-1.5">{[35, 42, 48, 54, 51, 62, 57, 68, 65, 76, 72, 78, 83, 79, 88, 82, 90, 86, 94, 88, 96, 91].map((height, index) => <div key={index} className={`flex-1 rounded-t-sm ${!healthy && index === 20 ? "bg-red-400" : "bg-emerald-300"}`} style={{ height: `${height}%` }} />)}</div><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4 text-xs"><span className="text-slate-500">GET /health</span><span className="font-medium text-slate-700">{healthy ? "200 · JSON healthy" : "503 · JSON unhealthy"}</span></div></CardContent></Card></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{ label: "Open incidents", value: String(incidents.filter(i => i.status !== "Resolved").length).padStart(2, "0"), note: "Needs attention", icon: InboxIcon }, { label: "Critical this shift", value: String(critical).padStart(2, "0"), note: "Last 8 hours", icon: Siren }, { label: "Mean response", value: "08m", note: "Target benchmark", icon: Clock3 }, { label: "Noise suppressed", value: "70%", note: "Correlation engine", icon: ShieldCheck }].map(stat => <Card key={stat.label} className="border-0 bg-white shadow-[0_8px_24px_rgba(30,41,59,.04)]"><CardContent className="p-5"><div className="flex items-center justify-between"><p className="text-xs font-medium text-slate-500">{stat.label}</p><stat.icon className="h-4 w-4 text-indigo-500" /></div><p className="mt-4 text-3xl font-semibold tracking-tight">{stat.value}</p><p className="mt-1 text-xs text-slate-400">{stat.note}</p></CardContent></Card>)}</section>
    <section><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-slate-400">Next best action</p><h2 className="mt-2 text-xl font-semibold tracking-tight">Operate with context</h2></div><Link href="/incidents" className="text-sm font-medium text-indigo-600 hover:text-indigo-800">View all incidents <ArrowRight className="ml-1 inline h-4 w-4" /></Link></div><div className="grid gap-4 md:grid-cols-3"><QuickLink href="/incidents" icon={Sparkles} title="Review incidents" description="Inspect AI decisions, approval gates, and resolution state." /><QuickLink href="/runbooks" icon={FileText} title="Browse runbooks" description="Search the local Markdown knowledge base used by Nexia." /><QuickLink href="/activity" icon={Users} title="Trace activity" description="Follow every alert, decision, and remediation event." /></div></section>
  </div>;
}

function InboxIcon(props: { className?: string }) { return <span className={props.className}>◌</span>; }
function QuickLink({ href, icon: Icon, title, description }: { href: string; icon: typeof FileText; title: string; description: string }) { return <Link href={href} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_8px_24px_rgba(30,41,59,.04)] transition hover:-translate-y-0.5 hover:border-indigo-200 hover:shadow-lg"><div className="flex items-start justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><Icon className="h-5 w-5" /></div><ArrowRight className="h-4 w-4 text-slate-300 transition group-hover:translate-x-1 group-hover:text-indigo-600" /></div><h3 className="mt-5 text-sm font-semibold">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{description}</p><Badge variant="outline" className="mt-4 text-[10px]">Open workspace</Badge></Link> }
