import React, { useMemo, useState } from "react";
import { BookOpen, FileText, Search } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function Runbooks() {
  const [query, setQuery] = useState("");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const runbooks = trpc.runbooks.list.useQuery().data ?? [];
  const filtered = useMemo(() => runbooks.filter(item => `${item.title} ${item.incidentType} ${item.severity}`.toLowerCase().includes(query.toLowerCase())), [runbooks, query]);
  const selected = filtered.find(item => item.id === selectedId) ?? filtered[0];
  return <div className="space-y-6"><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-slate-400">Knowledge base</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Runbooks</h2><p className="mt-2 text-sm text-slate-500">The Markdown procedures that ground every AI recommendation.</p></div><div className="grid gap-6 xl:grid-cols-[.75fr_1.25fr]"><Card className="border-0 bg-white shadow-sm"><CardHeader><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search runbooks" className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-9 pr-3 text-sm" /></div></CardHeader><CardContent className="space-y-2">{filtered.map(item => <button key={item.id} onClick={() => setSelectedId(item.id)} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left transition hover:border-indigo-200 ${selected?.id === item.id ? "border-indigo-200 bg-indigo-50/60" : "border-slate-100"}`}><span className="grid h-9 w-9 place-items-center rounded-lg bg-slate-100 text-slate-500"><FileText className="h-4 w-4" /></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{item.title}</span><span className="mt-1 block text-xs text-slate-400">{item.incidentType}</span></span><Badge variant="outline" className="text-[10px]">{item.severity}</Badge></button>)}{filtered.length === 0 && <p className="py-10 text-center text-sm text-slate-400">No runbooks found.</p>}</CardContent></Card><Card className="border-0 bg-white shadow-sm"><CardHeader><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><BookOpen className="h-5 w-5" /></span><div><p className="text-xs uppercase tracking-[0.18em] text-slate-400">Markdown reader</p><CardTitle className="mt-1">{selected?.title ?? "Select a runbook"}</CardTitle></div></div></CardHeader><CardContent>{selected ? <pre className="max-h-[560px] overflow-auto whitespace-pre-wrap rounded-2xl bg-[#101a2c] p-6 font-mono text-xs leading-6 text-slate-300">{selected.markdown}</pre> : <div className="py-24 text-center text-sm text-slate-400">Choose a runbook to read its full procedure.</div>}</CardContent></Card></div></div>;
}
