import React from "react";
import { Bell, Check, ExternalLink, LockKeyhole, PhoneCall, ServerCog, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

export default function Settings() {
  const providers = trpc.jobs.providers.useQuery();
  const status = providers.data;
  return <div className="space-y-6">
    <div><p className="text-xs font-medium uppercase tracking-[0.18em] text-slate-400">Workspace configuration</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Settings</h2><p className="mt-2 text-sm text-slate-500">Review approvals, notifications, provider connections, and job-ingestion endpoints.</p></div>
    <div className="grid gap-5 lg:grid-cols-2">
      <Card className="border-0 bg-white shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><LockKeyhole className="h-4 w-4 text-indigo-600" />Approval policy</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex items-center justify-between rounded-xl bg-emerald-50 p-4"><div><p className="text-sm font-semibold text-emerald-900">Human approval required</p><p className="mt-1 text-xs text-emerald-800/75">Every remediation action requires an explicit APPROVE confirmation.</p></div><Check className="h-5 w-5 text-emerald-600" /></div><div className="space-y-3 text-sm"><SettingLine label="Arbitrary commands" value="Blocked" /><SettingLine label="Delete or destructive actions" value="Blocked" /><SettingLine label="Simulation mode" value="Enabled" /></div></CardContent></Card>
      <Card className="border-0 bg-white shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><PhoneCall className="h-4 w-4 text-indigo-600" />OmniDim voice alerting</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex items-center justify-between rounded-xl bg-slate-50 p-4"><div><p className="text-sm font-semibold">Dispatch boundary</p><p className="mt-1 font-mono text-xs text-slate-500">POST /api/v1/calls/dispatch</p></div><Badge variant="outline">Simulation ready</Badge></div><p className="text-sm leading-6 text-slate-500">Critical incidents can prepare a voice-call payload containing service, severity, impact, and the recommended runbook action.</p><Button variant="outline" onClick={() => toast.info("OmniDim integration is ready for authorised credentials")}>View integration details <ExternalLink className="ml-2 h-3.5 w-3.5" /></Button></CardContent></Card>
      <Card className="border-0 bg-white shadow-sm lg:col-span-2"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><ServerCog className="h-4 w-4 text-indigo-600" />Background-job providers</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-3"><ProviderRow name="Internal jobs" configured={status?.internal.configured ?? true} endpoint="POST /api/jobs/heartbeat" /><ProviderRow name="Firecrawl" configured={status?.firecrawl.configured ?? false} endpoint="POST /api/webhooks/firecrawl" /><ProviderRow name="Apify" configured={status?.apify.configured ?? false} endpoint="POST /api/webhooks/apify" /></div><p className="mt-4 text-sm leading-6 text-slate-500">Internal workers can send signed heartbeats. Firecrawl and Apify can send lifecycle webhooks, while Poll provider reconciles live status when the corresponding server-side token is configured.</p></CardContent></Card>
      <Card className="border-0 bg-white shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Bell className="h-4 w-4 text-indigo-600" />Notifications</CardTitle></CardHeader><CardContent className="space-y-3"><SettingRow icon={Bell} title="Slack-style incident message" status="Enabled" /><SettingRow icon={PhoneCall} title="Critical voice alert" status="Prepared on demand" /><SettingRow icon={ShieldCheck} title="Post-mortem generation" status="Enabled" /></CardContent></Card>
      <Card className="border-0 bg-white shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><ServerCog className="h-4 w-4 text-indigo-600" />Service endpoints</CardTitle></CardHeader><CardContent className="space-y-3"><div className="rounded-xl border border-slate-100 p-4"><div className="flex items-center justify-between"><p className="font-mono text-sm">GET /health</p><Badge className="bg-emerald-50 text-emerald-700 hover:bg-emerald-50">JSON enabled</Badge></div><p className="mt-2 text-xs leading-5 text-slate-500">Reports the mock payment-service status as healthy or unhealthy for monitoring simulations.</p></div></CardContent></Card>
    </div>
  </div>;
}
function SettingLine({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between"><span className="text-slate-500">{label}</span><Badge variant="outline">{value}</Badge></div>; }
function ProviderRow({ name, configured, endpoint }: { name: string; configured: boolean; endpoint: string }) { return <div className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><div className="flex items-center justify-between gap-3"><p className="font-medium">{name}</p><Badge className={configured ? "bg-emerald-50 text-emerald-700 hover:bg-emerald-50" : "bg-amber-50 text-amber-700 hover:bg-amber-50"}>{configured ? "Connected" : "Webhook / token needed"}</Badge></div><p className="mt-2 font-mono text-xs text-slate-500">{endpoint}</p></div>; }
function SettingRow({ icon: Icon, title, status }: { icon: typeof Bell; title: string; status: string }) { return <div className="flex items-center gap-3 rounded-xl border border-slate-100 p-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-slate-100 text-slate-500"><Icon className="h-4 w-4" /></span><span className="flex-1 text-sm text-slate-700">{title}</span><span className="text-xs font-medium text-slate-500">{status}</span></div>; }
