import React, { useMemo, useState } from "react";
import { BellRing, Check, ChevronDown, Clock3, ExternalLink, FileText, Globe2, Pause, Play, Plus, ShieldCheck, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

type Frequency = "minute" | "five-minutes" | "hourly" | "daily";
type ResponseMode = "dashboard" | "email" | "omnidim";

function buildCron(frequency: Frequency, scheduleTime: string) {
  if (frequency === "minute") return "0 * * * * *";
  if (frequency === "five-minutes") return "0 */5 * * * *";
  if (frequency === "hourly") return "0 0 * * * *";
  const [hour, minute] = scheduleTime.split(":").map(Number);
  return `0 ${minute} ${hour} * * *`;
}

export function ConfiguredMonitorCard() {
  const [name, setName] = useState("My application");
  const [applicationUrl, setApplicationUrl] = useState("");
  const [healthUrl, setHealthUrl] = useState("");
  const [frequency, setFrequency] = useState<Frequency>("five-minutes");
  const [scheduleTime, setScheduleTime] = useState("09:00");
  const [timezone, setTimezone] = useState("UTC");
  const [runbookMarkdown, setRunbookMarkdown] = useState("# Application health failure\n\n1. Confirm the health check is failing.\n2. Review recent changes and dependency status.\n3. Restore the service only after human approval.");
  const [approvedAction, setApprovedAction] = useState("Restore or restart the application after explicit approval.");
  const [responseMode, setResponseMode] = useState<ResponseMode>("dashboard");
  const [responseContact, setResponseContact] = useState("");
  const [failureThreshold, setFailureThreshold] = useState("2");
  const configs = trpc.monitoring.list.useQuery();
  const create = trpc.monitoring.create.useMutation({ onSuccess: () => { void configs.refetch(); toast.success("Monitoring is scheduled", { description: "Nexia will check this application in the background." }); }, onError: error => toast.error("Could not create monitor", { description: error.message }) });
  const pause = trpc.monitoring.pause.useMutation({ onSuccess: () => void configs.refetch(), onError: error => toast.error("Could not pause monitor", { description: error.message }) });
  const resume = trpc.monitoring.resume.useMutation({ onSuccess: () => void configs.refetch(), onError: error => toast.error("Could not resume monitor", { description: error.message }) });
  const remove = trpc.monitoring.remove.useMutation({ onSuccess: () => { void configs.refetch(); toast.success("Monitor removed"); }, onError: error => toast.error("Could not remove monitor", { description: error.message }) });
  const checkSaved = trpc.monitoring.checkSaved.useMutation({ onSuccess: result => toast.success(result.overall === "healthy" ? "Application is healthy" : "Application needs attention", { description: result.overall === "healthy" ? "Both checks responded normally." : "Open the monitor details for the response." }), onError: error => toast.error("Check could not complete", { description: error.message }) });
  const canCreate = useMemo(() => Boolean(name.trim() && applicationUrl.trim() && runbookMarkdown.trim() && approvedAction.trim()), [name, applicationUrl, runbookMarkdown, approvedAction]);
  const submit = () => create.mutate({ name: name.trim(), applicationUrl: applicationUrl.trim(), healthUrl: healthUrl.trim() || undefined, cronExpression: buildCron(frequency, scheduleTime), timezone, runbookMarkdown, responseMode, responseContact: responseContact.trim() || undefined, failureThreshold: Number(failureThreshold), approvedAction });

  return <Card className="border-0 bg-white shadow-sm">
    <CardHeader className="border-b border-slate-100 pb-5"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-indigo-500" /><CardTitle>Set up automatic monitoring</CardTitle></div><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Tell Nexia where your application is and when to check it. You can start with only two URLs; the other settings already have safe defaults.</p></div><span className="shrink-0 rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-700">You approve every fix</span></div></CardHeader>
    <CardContent className="space-y-6 pt-6">
      <div className="grid gap-4 lg:grid-cols-2"><Step number="1" title="Which application should we watch?"><Field label="Application website" hint="The normal page users visit" value={applicationUrl} onChange={setApplicationUrl} placeholder="https://example.com" /><Field label="Health check URL" hint="Optional: a page that says whether the app is healthy" value={healthUrl} onChange={setHealthUrl} placeholder="https://example.com/health" /><p className="text-xs leading-5 text-slate-500"><Globe2 className="mr-1 inline h-3.5 w-3.5" />Use a public HTTPS URL. If you do not have a health URL, Nexia can still check whether the main website responds.</p></Step><Step number="2" title="How often should we check?"><div className="grid gap-3 sm:grid-cols-2"><Field label="Name this monitor" hint="For example, Student Task App" value={name} onChange={setName} placeholder="My application" /><label className="space-y-1.5"><span className="field-label block">Check frequency</span><span className="field-hint block">How often Nexia should look</span><select aria-label="Check frequency" value={frequency} onChange={event => setFrequency(event.target.value as Frequency)} className="input"><option value="minute">Every minute</option><option value="five-minutes">Every 5 minutes</option><option value="hourly">Every hour</option><option value="daily">Once a day</option></select></label></div>{frequency === "daily" && <div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="space-y-1.5"><span className="field-label block">Check at</span><span className="field-hint block">Your chosen local time</span><input aria-label="Daily check time" type="time" value={scheduleTime} onChange={event => setScheduleTime(event.target.value)} className="input" /></label><Field label="Time zone" hint="Use UTC if unsure" value={timezone} onChange={setTimezone} placeholder="UTC" /></div>}<p className="text-xs leading-5 text-slate-500"><Clock3 className="mr-1 inline h-3.5 w-3.5" />Nexia needs the site to be deployed before background checks can begin.</p></Step></div>
      <details className="group rounded-2xl border border-slate-200 bg-slate-50"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 p-4 text-sm font-semibold text-slate-700"><span className="flex items-center gap-2"><ChevronDown className="h-4 w-4 transition group-open:rotate-180" />Advanced settings <span className="font-normal text-slate-400">(optional)</span></span><span className="text-xs font-normal text-slate-400">Runbook, alerts, and safety</span></summary><div className="grid gap-5 border-t border-slate-200 p-4 lg:grid-cols-2"><label className="space-y-1.5"><span className="field-label block">What should Nexia do when it fails?</span><span className="field-hint block">Write the steps an operator should review</span><textarea value={runbookMarkdown} onChange={event => setRunbookMarkdown(event.target.value)} rows={7} className="input min-h-32 font-mono text-xs" /></label><div className="space-y-4"><label className="space-y-1.5"><span className="field-label block">Suggested recovery action</span><span className="field-hint block">This is only a proposal; it cannot run without approval</span><textarea value={approvedAction} onChange={event => setApprovedAction(event.target.value)} rows={3} className="input" /></label><div className="grid gap-3 sm:grid-cols-2"><label className="space-y-1.5"><span className="field-label block">Alert me through</span><span className="field-hint block">Dashboard is ready now</span><select aria-label="Alert mode" value={responseMode} onChange={event => setResponseMode(event.target.value as ResponseMode)} className="input"><option value="dashboard">Nexia dashboard</option><option value="email">Email-ready alert</option><option value="omnidim">OmniDim call-ready alert</option></select></label><Field label="Contact (optional)" hint={responseMode === "omnidim" ? "Phone number" : "Email address"} value={responseContact} onChange={setResponseContact} placeholder={responseMode === "omnidim" ? "+1 555 0100" : "you@example.com"} /></div><label className="space-y-1.5"><span className="field-label block">Failures before an incident</span><span className="field-hint block">Two failures helps avoid false alarms</span><input aria-label="Failures before an incident" type="number" min="1" max="10" value={failureThreshold} onChange={event => setFailureThreshold(event.target.value)} className="input" /></label><div className="rounded-xl bg-white p-3 text-xs leading-5 text-slate-600"><BellRing className="mr-1 inline h-3.5 w-3.5 text-indigo-500" />Alerts prepare the context for you. Nexia will never perform the recovery action automatically.</div></div></div></details>
      <div className="flex flex-wrap items-center gap-3"><Button disabled={!canCreate || create.isPending} onClick={submit} className="bg-[#111b2e] text-white hover:bg-[#202d46]"><Plus className="mr-2 h-4 w-4" />{create.isPending ? "Setting up…" : "Start monitoring"}</Button><span className="text-xs text-slate-400">You can pause or remove it at any time.</span></div>
      {configs.data && configs.data.length > 0 && <div className="space-y-3 border-t border-slate-100 pt-6"><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-slate-400" /><h3 className="text-sm font-semibold text-slate-700">Your monitors</h3></div>{configs.data.map(config => <div key={config.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-slate-800">{config.name}</p><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${config.enabled ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{config.enabled ? "Watching" : "Paused"}</span></div><p className="mt-2 break-all text-xs text-slate-500">{config.applicationUrl}</p><p className="mt-1 text-xs text-slate-400">{describeCron(config.cronExpression)} · Last result: {friendlyResult(config.lastStatus, config.lastResult)}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={() => checkSaved.mutate({ id: config.id })} disabled={checkSaved.isPending}><Check className="mr-1 h-3.5 w-3.5" />Check now</Button>{config.enabled ? <Button variant="outline" size="sm" onClick={() => pause.mutate({ id: config.id })}><Pause className="mr-1 h-3.5 w-3.5" />Pause</Button> : <Button variant="outline" size="sm" onClick={() => resume.mutate({ id: config.id })}><Play className="mr-1 h-3.5 w-3.5" />Resume</Button>}<Button variant="outline" size="sm" onClick={() => remove.mutate({ id: config.id })}><Trash2 className="mr-1 h-3.5 w-3.5" />Remove</Button></div></div></div>)}</div>}
    </CardContent>
  </Card>;
}
function Step({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 p-4"><div className="mb-4 flex items-center gap-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-indigo-50 text-sm font-bold text-indigo-600">{number}</span><h3 className="text-sm font-semibold text-slate-800">{title}</h3></div>{children}</section>; }
function Field({ label, hint, value, onChange, placeholder }: { label: string; hint: string; value: string; onChange: (value: string) => void; placeholder: string }) { return <label className="block space-y-1.5"><span className="field-label block">{label}</span><span className="field-hint block">{hint}</span><input value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} className="input" /></label>; }
function describeCron(cron: string) { if (cron === "0 * * * * *") return "Every minute"; if (cron === "0 */5 * * * *") return "Every 5 minutes"; if (cron === "0 0 * * * *") return "Every hour"; return "Daily schedule"; }
function friendlyResult(status?: string | null, detail?: string | null) { if (!status) return "Not checked yet"; if (status === "healthy") return "Healthy"; if (status === "unreachable") return "Could not reach the site"; if (status === "degraded") return "One check needs attention"; return detail || "Needs attention"; }
