import React, { useMemo, useState } from "react";
import { Globe2, HeartPulse, LockKeyhole, RefreshCw, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export function UrlMonitorCard() {
  const [applicationUrl, setApplicationUrl] = useState("");
  const [healthUrl, setHealthUrl] = useState("");
  const [result, setResult] = useState<Awaited<ReturnType<typeof trpc.monitoring.checkUrls.useMutation>>["data"]>();
  const presets = trpc.monitoring.testPresets.useQuery();
  const checkUrls = trpc.monitoring.checkUrls.useMutation({
    onSuccess: data => { setResult(data); toast.success("URL check completed", { description: data.overall === "healthy" ? "Both endpoints responded as expected." : "Review the endpoint results below." }); },
    onError: error => toast.error("URL check failed", { description: error.message }),
  });
  const canCheck = useMemo(() => applicationUrl.trim().length > 0 && !checkUrls.isPending, [applicationUrl, checkUrls.isPending]);
  const applyPreset = (preset: { applicationUrl: string; healthUrl: string }) => { setApplicationUrl(preset.applicationUrl); setHealthUrl(preset.healthUrl); setResult(undefined); };
  return <Card className="border-0 bg-white shadow-sm">
    <CardHeader className="pb-3"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Globe2 className="h-5 w-5 text-indigo-500" /><CardTitle>Check an application</CardTitle></div><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Enter a reachable application URL and optional health URL. Nexia checks them now and discards the submitted URLs and responses after the check.</p></div><Badge className="border-0 bg-emerald-50 text-emerald-700"><LockKeyhole className="mr-1 h-3 w-3" />Transient check</Badge></div></CardHeader>
    <CardContent className="space-y-5"><div className="grid gap-4 md:grid-cols-2"><label className="space-y-2"><span className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Application URL</span><input value={applicationUrl} onChange={event => setApplicationUrl(event.target.value)} placeholder="https://example.com" className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100" /></label><label className="space-y-2"><span className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Health URL <span className="font-normal normal-case tracking-normal">(optional)</span></span><input value={healthUrl} onChange={event => setHealthUrl(event.target.value)} placeholder="https://example.com/health" className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100" /></label></div><div className="flex flex-wrap items-center gap-2"><Button className="bg-[#111b2e] text-white hover:bg-[#202d46]" disabled={!canCheck} onClick={() => checkUrls.mutate({ applicationUrl: applicationUrl.trim(), healthUrl: healthUrl.trim() || undefined })}><RefreshCw className={`mr-2 h-4 w-4 ${checkUrls.isPending ? "animate-spin" : ""}`} />Check now</Button><span className="text-xs text-slate-400">Only public HTTP(S) endpoints are allowed.</span></div>{presets.data && <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-slate-400"><ShieldCheck className="h-4 w-4" />Testing presets</div><div className="mt-3 flex flex-wrap gap-2">{presets.data.map(preset => <Button key={preset.id} variant="outline" size="sm" onClick={() => applyPreset(preset)}>{preset.name}</Button>)}</div><p className="mt-3 text-xs leading-5 text-slate-500">Presets use public demo endpoints. The failure simulation intentionally returns HTTP 503 from the health URL.</p></div>}{result && <div className="grid gap-3 md:grid-cols-3"><ResultTile icon={<Globe2 className="h-4 w-4" />} label="Application" result={result.application} /><ResultTile icon={<HeartPulse className="h-4 w-4" />} label="Health endpoint" result={result.health} /><div className={`rounded-2xl p-4 ${result.overall === "healthy" ? "bg-emerald-50" : result.overall === "degraded" ? "bg-amber-50" : "bg-red-50"}`}><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Overall</p><p className="mt-2 text-lg font-semibold capitalize text-slate-900">{result.overall}</p><p className="mt-1 text-xs text-slate-500">Checked {new Date(result.checkedAt).toLocaleTimeString()}</p></div></div>}</CardContent>
  </Card>;
}
function ResultTile({ label, result, icon }: { label: string; result?: { ok: boolean; reachable: boolean; statusCode?: number; latencyMs: number; detail: string; healthStatus?: string }; icon: React.ReactNode }) { if (!result) return <div className="rounded-2xl bg-slate-50 p-4"><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">{icon}{label}</p><p className="mt-2 text-sm text-slate-400">Not provided</p></div>; return <div className={`rounded-2xl p-4 ${result.ok ? "bg-emerald-50" : "bg-red-50"}`}><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">{icon}{label}</p><p className="mt-2 text-lg font-semibold text-slate-900">{result.ok ? "Reachable" : result.reachable ? "Unhealthy" : "Unreachable"}</p><p className="mt-1 text-xs text-slate-500">{result.statusCode ? `HTTP ${result.statusCode}` : result.detail} · {result.latencyMs}ms</p>{result.healthStatus && <p className="mt-1 text-xs capitalize text-slate-500">JSON status: {result.healthStatus}</p>}</div>; }
