import React, { useMemo, useState } from "react";
import { CheckCircle2, Clock3, Globe2, HeartPulse, LockKeyhole, RefreshCw, ShieldCheck, XCircle } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

type CheckResult = NonNullable<Awaited<ReturnType<typeof trpc.monitoring.checkUrls.useMutation>>["data"]>;
type RecentCheck = CheckResult & { historyId: string };

export function UrlMonitorCard() {
  const [applicationUrl, setApplicationUrl] = useState("");
  const [healthUrl, setHealthUrl] = useState("");
  const [recentChecks, setRecentChecks] = useState<RecentCheck[]>([]);
  const [selectedId, setSelectedId] = useState<string>();
  const presets = trpc.monitoring.testPresets.useQuery();
  const checkUrls = trpc.monitoring.checkUrls.useMutation({
    onSuccess: data => {
      const historyId = `${data.checkedAt}-${data.application.url}`;
      const next = { ...data, historyId };
      setRecentChecks(current => [next, ...current.filter(item => item.application.url !== data.application.url || item.health?.url !== data.health?.url)].slice(0, 8));
      setSelectedId(historyId);
      toast.success("Check completed", { description: data.overall === "healthy" ? "Your application is reachable and healthy." : "The application needs attention. Select this check below for details." });
    },
    onError: error => toast.error("Check could not complete", { description: error.message }),
  });
  const canCheck = useMemo(() => applicationUrl.trim().length > 0 && !checkUrls.isPending, [applicationUrl, checkUrls.isPending]);
  const selected = recentChecks.find(item => item.historyId === selectedId) ?? recentChecks[0];
  const applyPreset = (preset: { applicationUrl: string; healthUrl: string }) => { setApplicationUrl(preset.applicationUrl); setHealthUrl(preset.healthUrl); setSelectedId(undefined); };
  const submit = () => checkUrls.mutate({ applicationUrl: applicationUrl.trim(), healthUrl: healthUrl.trim() || undefined });

  return <Card className="border-0 bg-white shadow-sm">
    <CardHeader className="pb-3"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Globe2 className="h-5 w-5 text-indigo-500" /><CardTitle>Check an application</CardTitle></div><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Enter the website and optional health URL, then select <strong>Submit and check</strong>. Recent checks stay only in this browser session and are not saved to the database.</p></div><Badge className="border-0 bg-emerald-50 text-emerald-700"><LockKeyhole className="mr-1 h-3 w-3" />Not saved</Badge></div></CardHeader>
    <CardContent className="space-y-5"><div className="grid gap-4 md:grid-cols-2"><UrlField label="Application URL" hint="The normal page users visit" value={applicationUrl} onChange={setApplicationUrl} placeholder="https://example.com" /><UrlField label="Health URL" hint="Optional: a page that reports app health" value={healthUrl} onChange={setHealthUrl} placeholder="https://example.com/health" /></div><div className="flex flex-wrap items-center gap-3"><Button className="bg-[#111b2e] text-white hover:bg-[#202d46]" disabled={!canCheck} onClick={submit}><RefreshCw className={`mr-2 h-4 w-4 ${checkUrls.isPending ? "animate-spin" : ""}`} />{checkUrls.isPending ? "Checking…" : "Submit and check"}</Button><span className="text-xs text-slate-400">Only public HTTP(S) endpoints are allowed.</span></div>{presets.data && <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-slate-400"><ShieldCheck className="h-4 w-4" />Try a test example</div><div className="mt-3 flex flex-wrap gap-2">{presets.data.map(preset => <Button key={preset.id} variant="outline" size="sm" onClick={() => applyPreset(preset)}>{preset.name}</Button>)}</div><p className="mt-3 text-xs leading-5 text-slate-500">These examples use public demo endpoints. Choose one, then press Submit and check.</p></div>}
      {recentChecks.length > 0 && <div className="space-y-3 border-t border-slate-100 pt-5"><div className="flex items-center justify-between gap-3"><div><div className="flex items-center gap-2"><Clock3 className="h-4 w-4 text-slate-400" /><h3 className="text-sm font-semibold text-slate-700">Recently checked URLs</h3></div><p className="mt-1 text-xs text-slate-400">Session-only history · cleared when this session ends</p></div><span className="text-xs font-semibold text-slate-400">{recentChecks.length} check{recentChecks.length === 1 ? "" : "s"}</span></div><div className="overflow-x-auto rounded-2xl border border-slate-200"><table className="w-full min-w-[520px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-[0.12em] text-slate-400"><tr><th className="px-4 py-3 font-semibold">Application</th><th className="px-4 py-3 font-semibold">Checked</th><th className="px-4 py-3 font-semibold">Result</th><th className="px-4 py-3 font-semibold">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{recentChecks.map(item => <tr key={item.historyId} className={item.historyId === selected?.historyId ? "bg-indigo-50/60" : "bg-white"}><td className="max-w-[220px] truncate px-4 py-3 font-medium text-slate-700" title={item.application.url}>{item.application.url}</td><td className="whitespace-nowrap px-4 py-3 text-xs text-slate-500">{new Date(item.checkedAt).toLocaleTimeString()}</td><td className="px-4 py-3"><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-semibold ${item.overall === "healthy" ? "bg-emerald-50 text-emerald-700" : item.overall === "degraded" ? "bg-amber-50 text-amber-700" : "bg-red-50 text-red-700"}`}>{item.overall === "healthy" ? <CheckCircle2 className="h-3 w-3" /> : <XCircle className="h-3 w-3" />}{item.overall}</span></td><td className="px-4 py-3"><Button variant="outline" size="sm" onClick={() => setSelectedId(item.historyId)}>View status</Button></td></tr>)}</tbody></table></div></div>}
      {selected && <div className={`rounded-2xl p-4 ${selected.overall === "healthy" ? "bg-emerald-50" : selected.overall === "degraded" ? "bg-amber-50" : "bg-red-50"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">Selected check status</p><p className="mt-1 text-lg font-semibold capitalize text-slate-900">{selected.overall === "healthy" ? "Application is healthy" : selected.overall === "degraded" ? "Application partly needs attention" : "Application could not be verified"}</p><p className="mt-1 break-all text-xs text-slate-500">{selected.application.url} · checked {new Date(selected.checkedAt).toLocaleString()}</p></div><Badge className="border-0 bg-white/70 text-slate-700">{selected.overall}</Badge></div><div className="mt-4 grid gap-3 md:grid-cols-2"><ResultTile icon={<Globe2 className="h-4 w-4" />} label="Application page" result={selected.application} /><ResultTile icon={<HeartPulse className="h-4 w-4" />} label="Health check" result={selected.health} /></div></div>}
    </CardContent>
  </Card>;
}
function UrlField({ label, hint, value, onChange, placeholder }: { label: string; hint: string; value: string; onChange: (value: string) => void; placeholder: string }) { return <label className="block space-y-1.5"><span className="field-label block">{label}</span><span className="field-hint block">{hint}</span><input value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} className="input" /></label>; }
function ResultTile({ label, result, icon }: { label: string; result?: { ok: boolean; reachable: boolean; statusCode?: number; latencyMs: number; detail: string; healthStatus?: string }; icon: React.ReactNode }) { if (!result) return <div className="rounded-2xl bg-white/70 p-4"><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">{icon}{label}</p><p className="mt-2 text-sm text-slate-500">No separate health URL was provided.</p></div>; return <div className={`rounded-2xl bg-white/70 p-4 ${result.ok ? "" : "ring-1 ring-red-200"}`}><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">{icon}{label}</p><p className="mt-2 text-lg font-semibold text-slate-900">{result.ok ? "Reachable" : result.reachable ? "Unhealthy" : "Unreachable"}</p><p className="mt-1 text-xs text-slate-500">{result.statusCode ? `HTTP ${result.statusCode}` : result.detail} · {result.latencyMs}ms</p>{result.healthStatus && <p className="mt-1 text-xs capitalize text-slate-500">JSON status: {result.healthStatus}</p>}</div>; }
